// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProgressBar is an autogenerated mock type for the ProgressBar type
type ProgressBar struct {
	mock.Mock
}

// Add provides a mock function with given fields: num
func (_m *ProgressBar) Add(num int) error {
	ret := _m.Called(num)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(num)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Finish provides a mock function with given fields:
func (_m *ProgressBar) Finish() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Write provides a mock function with given fields: p
func (_m *ProgressBar) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProgressBar creates a new instance of ProgressBar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProgressBar(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProgressBar {
	mock := &ProgressBar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}